# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
    branches: [ master, feature/test ]
  pull_request:
    branches: [ master, feature/test ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: 'playground-s-11-b525daf3'
      SERVICE_NAME: "hello-world"
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout code
      uses: actions/checkout@v2
    
  #  - run: echo "::set-env name=SERVICE_ACCOUNT_KEY::${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
        
    - name: Activate Service Account 
      env: 
        SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "$SERVICE_ACCOUNT_KEY" > ${HOME}/gcloud.json
        gcloud --quiet auth activate-service-account --key-file=${HOME}/gcloud.json
        gcloud config set project $PROJECT_ID
 #       gcloud auth configure-docker
    
    - name: check gcloud info
      run: gcloud info
    
    - name: set environment variable of git short sha
      run: |
         echo "::set-env name=GITHUB_SHA_SHORT::$(git rev-parse --short HEAD)"

    - name: build docker image
      run: docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_REF#refs/heads/}-${GITHUB_SHA_SHORT} .
    
    - name: configure docker to use gcloud cli
      run: gcloud auth configure-docker -q

    - name: push docker image
      run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_REF#refs/heads/}-${GITHUB_SHA_SHORT}
    
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v2.x
    
    - name: check envs vars
      run: |
        echo "Slug variables"
        echo "   ref        : ${{ env.GITHUB_REF_SLUG }}"
        echo "   head ref   : ${{ env.GITHUB_HEAD_REF_SLUG }}"
        echo "   base ref   : ${{ env.GITHUB_BASE_REF_SLUG }}"
        echo "   event ref  : ${{ env.GITHUB_EVENT_REF_SLUG }}"
        echo "   repository : ${{ env.GITHUB_REPOSITORY_SLUG }}"
        echo "Slug URL variables"
        echo "   ref        : ${{ env.GITHUB_REF_SLUG_URL }}"
        echo "   head ref   : ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
        echo "   base ref   : ${{ env.GITHUB_BASE_REF_SLUG_URL }}"
        echo "   event ref  : ${{ env.GITHUB_EVENT_REF_SLUG_URL }}"
        echo "   repository : ${{ env.GITHUB_REPOSITORY_SLUG_URL }}"
        echo "Short SHA variables"
        echo "   sha        : ${{ env.GITHUB_SHA_SHORT }}"
