# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
    branches: [ master, feature/**, develop, qa, mock_prod, prod] 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: 'playground-s-11-c5651105'
      SERVICE_NAME: "hello-world"
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout code
      uses: actions/checkout@v2
    
  #  - run: echo "::set-env name=SERVICE_ACCOUNT_KEY::${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
        
    - name: Activate Service Account 
      env: 
        SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "$SERVICE_ACCOUNT_KEY" > ${HOME}/gcloud.json
        gcloud --quiet auth activate-service-account --key-file=${HOME}/gcloud.json --project=$PROJECT_ID
      continue-on-error: true
 #       gcloud auth configure-docker
    
    - name: check gcloud info
      run: gcloud info
    
    - name: set environment variable of git short sha
      run: |
         echo "::set-env name=GITHUB_SHA_SHORT::$(git rev-parse --short HEAD)"
   
    - name: check branch
      run: |
        CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
        echo ${CURRENT_BRANCH::7}
         
    - name: set docker tag
      run: |
        CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
        
        if [ $CURRENT_BRANCH == develop ];
         then
          echo ::set-env name=BRANCH_TAG::dev
          
        elif [ $CURRENT_BRANCH == qa ];
         then
          echo ::set-env name=BRANCH_TAG::qa
        
        elif [ $CURRENT_BRANCH == mock_prod ];
         then
          echo ::set-env name=BRANCH_TAG::mck_prd
          
        elif [ $CURRENT_BRANCH == master ];
         then
          echo ::set-env name=BRANCH_TAG::master
          
        elif [ `echo ${CURRENT_BRANCH::7}` == feature ];
         then
           FEATURE-TAG=$(echo $CURRENT_BRANCH | sed 's/\//-/')
           echo ::set-env name=BRANCH_TAG::${FEATURE-TAG}
         
        else
          echo "merge to correct branch"
        fi
        
    - name: check branch tags
      run: |
        echo ${BRANCH_TAG}
           
    - name: build docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${BRANCH_TAG} \
                     -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${BRANCH_TAG}-${GITHUB_SHA_SHORT} .
    
    - name: configure docker to use gcloud cli
      run: gcloud auth configure-docker -q

    - name: push docker image
      run: |
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME
         
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v2.x
