# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: "playground-s-11-61a09026"
      SERVICE_NAME: "hello-world"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout code
      uses: actions/checkout@v2
    
    - name: Get the version
      id: get_tag_name
      run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
    
    - name: show git-tag
      run: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}
      
    - name: setup gcloud cli
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: 'playground-s-11-cf7b54f7'
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
      
    - name: check gcloud info
      run: gcloud info

    - name: build docker image
      run: docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ env.GITHUB_SHA_SHORT }} .
    
    - name: configure docker to use gcloud cli
      run: gcloud auth configure-docker -q

    - name: push docker image
      run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ env.GITHUB_SHA_SHORT }}
