name: Terraform

on:
  push:
    branches:
      - master
      - feature/**
      - develop
      - qa
      - mock_prod
      - prod
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
    
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  
defaults:
  run:
    working-directory: terraform
  
jobs:
  terraform:
    runs-on: ubuntu-latest
    
    env:
      PROJECT_ID: 'playground-s-11-a285c098'
    
    steps:
    
    - name: checkout code
      uses: actions/checkout@v2
   
    - name: GCloud - Setup
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      
#    - name: activate service account 
#      env: 
#        SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
#      run: |
#        echo "$SERVICE_ACCOUNT_KEY" > ${HOME}/gcloud.json
#        gcloud --quiet auth activate-service-account --key-file=${HOME}/gcloud.json --project=${PROJECT_ID}

    - name: setup terraform
      uses: hashicorp/setup-terraform@v1
       
    - name: terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: terraform init
      id: init
      run: terraform init

    - name: terraform validate
      id: validate
      run: terraform validate

    - name: terraform plan
      id: plan
      run: terraform plan -out=terraform.plan -var 'project_id=${PROJECT_ID}'
 #     continue-on-error: true
        
    - name: terraform apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve -var 'project_id=${PROJECT_ID}'
