name: Vars

# Controls when the action will run.
on:
  push:
    branches: [ master, feature/test ]
  pull_request:
    branches: [ master, feature/test ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: "playground-s-11-61a09026"
      SERVICE_NAME: "hello-world"
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: check branch
      id: vars
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        
    - name: verify branch
      run: |
        echo "Branch: ${{ steps.vars.outputs.branch }}"
           
    - name: versioning
      if: (contains(steps.vars.outputs.branch, 'feature/**'))
      run: |
        echo "::set-env name=VERSION::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/')"
        echo ${{ env.VERSION }}
    
    - name: Extract Git short sha
      run: |
         echo "::set-env name=sha_short::$(git rev-parse --short HEAD)"
         echo ${{ env.sha_short }}
         
    - name: check commit
      run: |
         x=echo $COMMIT | cut -b -7
         echo $x
      
    - name: test
      run: echo "${GITHUB_REF#refs/heads/}"
